[package]
name = "my-app"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.6", features = [
  "postgres",
  "runtime-tokio-rustls",
  "chrono",
] }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
serde = "1.0"
chrono = "0.4.38"
dotenv = "0.15"
